"""The recompiled game's calls into the runtime's PsyQ libraries (com.recomp.ps1 recomp mode).

N64Recomp's output calls every PsyQ function by name, as <name>_recomp(rdram, ctx) with the
MIPS o32 arguments in ctx (a0-a3, then the stack from sp + 16). The libraries are the wasm2c
module "ps1hle", whose exports take those arguments as plain values (PS1 addresses are its
addresses). This writes, for each PsyQ function the game has (ps1_syms.py's psyq.txt):

  - a wrapper calling the module's export with the arguments it takes, the result in v0
    (v0/v1 for 64-bit results);
  - printf / sprintf: the variadic arguments copied to a buffer in guest memory (wasm32
    passes them in memory);
  - otherwise a stub that logs the call once (ps1r_missing) and returns 0.

    python gen_hle_wrappers.py <ps1hle_guest.h> <psyq.txt> <out dir>
writes <out>/ps1_hle_wrappers.c and <out>/ps1_hle_decls.h (declarations the generated code
is compiled with).
"""
import os
import re
import sys

EXPORT_RE = re.compile(r"^(u32|u64|void|f32|f64|s32|s64)\s+w2c_ps1hle_(\w+)\(w2c_ps1hle\*(?:\s*\w*)?(?:,\s*([^)]*))?\);")
# the export's own name (wasm2c escapes some characters in the C name: _bu_init -> 0x5Fbu_init)
EXPORT_NAME_RE = re.compile(r"^/\* export: '([^']+)' \*/")
# PsyQ names the runtime's libraries give another name (they'd clash with the host's C library)
ALIASES = {"open": "ps1_open", "read": "ps1_read", "write": "ps1_write", "lseek": "ps1_lseek", "close": "ps1_close"}
# fixed arguments before the variadic ones
VARIADIC = {"printf": 1, "sprintf": 2}
# in the runtime itself (recomp_ps1.c, recomp_libc.c)
RUNTIME = {"OpenTh", "ChangeTh", "CloseTh", "GetGp", "setjmp", "longjmp", "memcpy", "memmove", "memset", "memcmp", "strlen", "strcpy", "strncpy", "strcat",
           "strcmp", "strncmp", "strchr", "strrchr", "abs"}


def arg(i):
    if i < 4:
        return f"(u32)ctx->r{4 + i}"
    return f"(u32)MEM_W({16 + 4 * (i - 4)}, ctx->r29)"


def main():
    header, psyq_path, out = sys.argv[1:4]
    exports = {}
    with open(header, encoding="utf-8") as f:
        export_name = None
        for line in f:
            n = EXPORT_NAME_RE.match(line.strip())
            if n:
                export_name = n.group(1)
                continue
            m = EXPORT_RE.match(line.strip())
            if m:
                params = [p.strip() for p in (m.group(3) or "").split(",") if p.strip()]
                exports[export_name or m.group(2)] = (m.group(1), params, m.group(2))
            export_name = None
    with open(psyq_path, encoding="utf-8") as f:
        names = [n.strip() for n in f if n.strip()]

    lines = ["/* Generated by gen_hle_wrappers.py - do not edit. The game's PsyQ calls -> the",
             " * runtime's libraries (ps1hle). */",
             '#include "recomp.h"',
             '#include "ps1hle_guest.h"',
             "",
             "extern w2c_ps1hle ps1r_hle;",
             "void ps1r_enter(recomp_context *ctx);",
             "void ps1r_leave(void);",
             "void ps1r_missing(const char *name, recomp_context *ctx);",
             "u32 w2c_ps1hle_port_recomp_varargs(w2c_ps1hle *);",
             ""]
    decls = ["/* Generated by gen_hle_wrappers.py - do not edit. */",
             '#include "recomp.h"']
    wrapped = missing = 0
    for name in names:
        if name in RUNTIME:
            decls.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx);")
            lines.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx);")
            continue
        decls.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx);")
        exp = exports.get(ALIASES.get(name, name))
        ok = exp is not None and exp[0] in ("u32", "u64", "void", "s32", "s64") and \
            all(p in ("u32", "s32") for p in exp[1])
        if not ok:
            lines.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx) {{ ps1r_missing(\"{name}\", ctx); }}")
            missing += 1
            continue
        ret, params, cname = exp
        if name in VARIADIC:
            fixed = VARIADIC[name]
            if len(params) != fixed + 1:
                lines.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx) {{ ps1r_missing(\"{name}\", ctx); }}")
                missing += 1
                continue
            body = [f"    const u32 va = w2c_ps1hle_port_recomp_varargs(&ps1r_hle);",
                    "    int i;",
                    f"    for (i = 0; i < 24; i++) MEM_W(4 * i, va) = (int32_t)("
                    f"(i + {fixed} < 4) ? (u32)(&ctx->r4)[i + {fixed}] : (u32)MEM_W(16 + 4 * (i + {fixed} - 4), ctx->r29));"]
            call_args = [arg(i) for i in range(fixed)] + ["va"]
        else:
            body = []
            call_args = [arg(i) for i in range(len(params))]
        call = f"w2c_ps1hle_{cname}(&ps1r_hle{''.join(', ' + a for a in call_args)})"
        lines.append(f"void {name}_recomp(uint8_t *rdram, recomp_context *ctx)")
        lines.append("{")
        lines.append("    ps1r_enter(ctx);")
        lines.extend(body)
        if ret in ("u32", "s32"):
            lines.append(f"    ctx->r2 = (gpr)(int32_t){call};")
        elif ret in ("u64", "s64"):
            lines.append(f"    {{ const u64 r = (u64){call};")
            lines.append("      ctx->r2 = (gpr)(int32_t)(u32)r; ctx->r3 = (gpr)(int32_t)(u32)(r >> 32); }")
        else:
            lines.append(f"    {call};")
        lines.append("    ps1r_leave();")
        lines.append("}")
        wrapped += 1

    # by name, for the live recompiler (which calls them from the code it makes)
    lines.append("")
    lines.append("typedef struct { const char *name; void (*func)(uint8_t *, recomp_context *); } Ps1rHleEntry;")
    lines.append("const Ps1rHleEntry ps1r_hle_table[] = {")
    for name in names:
        lines.append(f'    {{"{name}_recomp", {name}_recomp}},')
    lines.append("    {0, 0},")
    lines.append("};")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "ps1_hle_wrappers.c"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(out, "ps1_hle_decls.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(decls) + "\n")
    print(f"gen_hle_wrappers: {wrapped} PsyQ functions wrapped, {missing} not in the runtime (stubs)")


if __name__ == "__main__":
    main()
