# Recomp mode: a PS1 game recompiled from its disc by N64Recomp (PS1 mode), on the runtime's
# PsyQ libraries (port/guest), on Windows x64.
#
#   include(<com.recomp.ps1>/Runtime/cmake/Ps1Recomp.cmake)
#   ps1_recomp_game(NAME dw TITLE "Digimon World" PACKAGE com.recomp.digimonworld
#                   GENERATED <N64Recomp output: funcs_*.c, funcs.h, recomp_overlays.inl>
#                   SYMS <the game's Recomp folder: syms.toml, psyq.txt, data_symbols.txt, game.json>
#                   [SECTION_FILES <ps1_rom.py's section_files.c> (default SYMS/section_files.c)]
#                   INCLUDES <PsyQ SDK headers (psyq_headers/.../include)>
#                   [DISC <default disc image>])
#
# Makes <name>_recomp_game (a static library: the game as a Ps1wModule, ps1w_module_<name>_recomp,
# which the editor's com.recomp.ps1 addon links - tools/recomp/build_recomp.ps1 publishes it) and
# <name>_recomp(.exe): the standalone host (window, --headless, --dump, --wav ... as the wasm
# build's) running it. Pieces of the library:
#   ps1hle      the PsyQ libraries (port/guest/*.c) compiled to WebAssembly and translated to
#               C by wasm2c, like a wasm game build without the game; its memory is the guest
#               memory the recompiled code shares (Source/Wasm/ps1w.h)
#   wrappers    o32 calls from the game -> the module's exports (tools/recomp/gen_hle_wrappers.py)
#   runtime     runtime/recomp: boot, code lookup, overlays, callbacks, GTE, setjmp
# The generated C is game code made from the player's disc: it is built locally, never committed.
#
# PS1_RECOMP_LIVE (Recomp (live), 64-bit PCs): no generated C. The program carries N64Recomp's
# LiveRecomp (com.recomp.ps1's ThirdParty/N64Recomp, PS1 mode) and recompiles the game from the
# player's disc when it boots (runtime/recomp/ps1_live.cpp), from the game's syms.toml and
# game.json (SYMS, or ps1r_set_data_dir / PS1_RECOMP_DIR). It holds no game code. The library
# for the addon is then <name>_recomp_all: the game library and the recompiler's merged.
#
# Every global of the library is the same for every game ("ps1hle", "ps1r_"): one recompiled
# game per editor project (other PS1 games there build in Decomp mode).
cmake_minimum_required(VERSION 3.20)

include("${CMAKE_CURRENT_LIST_DIR}/Ps1Game.cmake")
option(PS1_RECOMP_LIVE "recompile the game at boot (LiveRecomp) instead of building N64Recomp's C" OFF)
set(PS1_N64RECOMP_DIR "${CMAKE_CURRENT_LIST_DIR}/../../ThirdParty/N64Recomp" CACHE PATH "com.recomp.ps1's N64Recomp")

function(ps1_recomp_game)
    cmake_parse_arguments(G "" "NAME;TITLE;PACKAGE;GENERATED;SYMS;SECTION_FILES;DISC;RAM_SIZE" "INCLUDES" ${ARGN})
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    set(PY "${Python3_EXECUTABLE}")
    set(PORT_DIR "${PS1_RUNTIME_DIR}/port")
    set(TOOLS "${PS1_RUNTIME_DIR}/tools")
    set(RECOMP_DIR "${PS1_RUNTIME_DIR}/recomp")
    get_filename_component(SOURCE_WASM_DIR "${PS1_RUNTIME_DIR}/../Source/Wasm" ABSOLUTE)
    set(GEN_DIR "${CMAKE_BINARY_DIR}/gen")
    set(HLE_DIR "${CMAKE_BINARY_DIR}/hle")
    file(MAKE_DIRECTORY "${GEN_DIR}" "${HLE_DIR}")
    if(NOT G_SECTION_FILES)
        set(G_SECTION_FILES "${G_SYMS}/section_files.c")
    endif()
    if(NOT G_RAM_SIZE)
        set(G_RAM_SIZE 0x200000)
    endif()
    if(NOT EXISTS "${G_SYMS}/psyq.txt" OR (NOT PS1_RECOMP_LIVE AND NOT EXISTS "${G_GENERATED}/funcs.h"))
        message(FATAL_ERROR "ps1_recomp_game: SYMS needs ps1_syms.py's output, GENERATED N64Recomp's (unless PS1_RECOMP_LIVE)")
    endif()

    # ---- game configuration for the libraries and the host (no movies or overlays of the
    # port: the game plays and loads them itself)
    set(disc_name "")
    set(disc_path "")
    if(G_DISC)
        file(TO_NATIVE_PATH "${G_DISC}" disc_path)
        string(REPLACE "\\" "\\\\" disc_path "${disc_path}")
        get_filename_component(disc_name "${G_DISC}" NAME)
    endif()
    file(WRITE "${GEN_DIR}/ps1_game_config.h.new"
        "/* Generated by Ps1Recomp.cmake for ${G_NAME} - do not edit. */\n"
        "#ifndef PS1_GAME_CONFIG_H\n#define PS1_GAME_CONFIG_H\n"
        "#define PS1_GAME_TITLE \"${G_TITLE}\"\n"
        "#define PS1_BOOT_EXE \"\"\n#define PS1_BOOT_EXE_NAME \"\"\n"
        "#define PS1_BSS_END 0u\n#define PS1_RAM_SIZE ${G_RAM_SIZE}u\n"
        "#define PS1_DEFAULT_DISC \"${disc_path}\"\n#define PS1_DEFAULT_DISC_NAME \"${disc_name}\"\n"
        "#define PS1_EXTRACTED_DISC \"\"\n"
        "#define PS1_MOVIE_COUNT 0\n#define PS1_MOVIES { 0 }\n#define PS1_MOVIE_NOSKIP_MASK 0u\n"
        "#endif\n")
    file(COPY_FILE "${GEN_DIR}/ps1_game_config.h.new" "${GEN_DIR}/ps1_game_config.h" ONLY_IF_DIFFERENT)

    # ---- the libraries as a wasm module --------------------------------------------------------
    _ps1_find_tool(PS1_WASI_SDK "wasi-sdk-*")
    _ps1_find_tool(PS1_WABT "wabt-*")
    set(WASM_CC "${PS1_WASI_SDK}/bin/clang${CMAKE_HOST_EXECUTABLE_SUFFIX}")
    set(WASM_LD "${PS1_WASI_SDK}/bin/wasm-ld${CMAKE_HOST_EXECUTABLE_SUFFIX}")
    set(WASI_LIB "${PS1_WASI_SDK}/share/wasi-sysroot/lib/wasm32-wasip1")
    file(GLOB WASM_RT_BUILTINS "${PS1_WASI_SDK}/lib/clang/*/lib/wasm32-unknown-wasip1/libclang_rt.builtins.a")
    set(WASM2C "${PS1_WABT}/bin/wasm2c${CMAKE_HOST_EXECUTABLE_SUFFIX}")
    set(cflags --target=wasm32 -O2 -mllvm -wasm-enable-sjlj -mexception-handling
        -Xclang -no-enable-noundef-analysis -fno-delete-null-pointer-checks -std=gnu99 -ffreestanding -nostdlibinc -fno-builtin
        -fno-strict-aliasing -fwrapv -funsigned-char -Wno-everything
        -include "${PORT_DIR}/include/port_prelude.h" -I "${PORT_DIR}/include" -I "${GEN_DIR}"
        -DPORT=1 -DPORT_HOST_GPU=1)
    # the PsyQ headers the libraries are written against (struct layouts the game shares)
    foreach(i IN LISTS G_INCLUDES)
        list(APPEND cflags -I "${i}")
    endforeach()
    file(GLOB hle_sources CONFIGURE_DEPENDS "${PORT_DIR}/guest/*.c" "${PORT_DIR}/guest/wasm/*.c")
    # the GPU runs in the host (Source/Wasm/ps1w_gpu.c); boot, overlays and the port's movie
    # player belong to decomp builds
    list(FILTER hle_sources EXCLUDE REGEX "/(gpu|boot|overlays|movie)[.]c$")
    list(APPEND hle_sources "${RECOMP_DIR}/hle/recomp_hle.c")
    set(objs "")
    foreach(src IN LISTS hle_sources)
        get_filename_component(stem "${src}" NAME_WE)
        set(obj "${HLE_DIR}/obj/${stem}.o")
        add_custom_command(OUTPUT "${obj}"
            COMMAND "${WASM_CC}" ${cflags} -MD -MF "${obj}.d" -c "${src}" -o "${obj}"
            DEPENDS "${src}" DEPFILE "${obj}.d" COMMENT "wasm ${stem}.c" VERBATIM)
        list(APPEND objs "${obj}")
    endforeach()
    # PS1 RAM first, as a placeholder with the game's data symbols at their addresses (the
    # libraries use PsyQ's globals where the game has them); the libraries' own data, stack
    # and heap follow, up to PS1W_HEAP_END - the layout of a wasm game build.
    add_custom_command(OUTPUT "${HLE_DIR}/ps1_symbols.s"
        COMMAND "${PY}" "${TOOLS}/recomp/make_hle_symbols.py" "${G_SYMS}/data_symbols.txt" "${HLE_DIR}/ps1_symbols.s"
            "--ram-size=${G_RAM_SIZE}"
        DEPENDS "${G_SYMS}/data_symbols.txt" "${TOOLS}/recomp/make_hle_symbols.py" "${TOOLS}/gen_symbols.py"
        COMMENT "the game's data symbols" VERBATIM)
    set(sym_obj "${HLE_DIR}/obj/ps1_symbols.o")
    add_custom_command(OUTPUT "${sym_obj}"
        COMMAND "${WASM_CC}" --target=wasm32 -c "${HLE_DIR}/ps1_symbols.s" -o "${sym_obj}"
        DEPENDS "${HLE_DIR}/ps1_symbols.s" VERBATIM)
    set(wasm "${HLE_DIR}/ps1hle.wasm")
    add_custom_command(OUTPUT "${wasm}"
        COMMAND "${PY}" "${TOOLS}/wasm_link.py" "${WASM_LD}" --no-entry --export-all
            --no-stack-first -z stack-size=524288 --global-base=2147483648
            --initial-memory=2155806720 --max-memory=2155806720
            "--allow-undefined-file=${TOOLS}/wasm_imports.txt" --error-limit=0
            "${sym_obj}" ${objs} "${WASI_LIB}/libsetjmp.a" "${WASI_LIB}/libc.a" ${WASM_RT_BUILTINS}
            -o "${wasm}"
        DEPENDS "${sym_obj}" ${objs} "${TOOLS}/wasm_imports.txt" "${TOOLS}/wasm_link.py"
        COMMENT "wasm-ld ps1hle.wasm" VERBATIM)
    set(w2c_count 4)
    set(w2c_c "")
    math(EXPR last "${w2c_count} - 1")
    foreach(i RANGE ${last})
        list(APPEND w2c_c "${HLE_DIR}/ps1hle_guest_${i}.c")
    endforeach()
    add_custom_command(OUTPUT ${w2c_c} "${HLE_DIR}/ps1hle_guest.h" "${HLE_DIR}/ps1hle_guest-impl.h"
        COMMAND "${PY}" "${TOOLS}/wasm_to_c.py" "${WASM2C}" "${wasm}" "${HLE_DIR}" ps1hle ${w2c_count}
            "--runtime-include=${SOURCE_WASM_DIR}/"
        DEPENDS "${wasm}" "${TOOLS}/wasm_to_c.py"
        COMMENT "wasm2c ps1hle.wasm" VERBATIM)

    # ---- the game's calls into it ----------------------------------------------------------------
    add_custom_command(OUTPUT "${HLE_DIR}/ps1_hle_wrappers.c" "${HLE_DIR}/ps1_hle_decls.h"
        COMMAND "${PY}" "${TOOLS}/recomp/gen_hle_wrappers.py" "${HLE_DIR}/ps1hle_guest.h" "${G_SYMS}/psyq.txt" "${HLE_DIR}"
        DEPENDS "${HLE_DIR}/ps1hle_guest.h" "${G_SYMS}/psyq.txt" "${TOOLS}/recomp/gen_hle_wrappers.py"
        COMMENT "PsyQ wrappers" VERBATIM)

    # ---- the program --------------------------------------------------------------------------
    if(PS1_RECOMP_LIVE)
        if(NOT TARGET LiveRecomp)
            add_subdirectory("${PS1_N64RECOMP_DIR}" "${CMAKE_BINARY_DIR}/n64recomp" EXCLUDE_FROM_ALL)
        endif()
        set(generated_c "")
        set(game_sources "${RECOMP_DIR}/ps1_live.cpp" "${PS1_N64RECOMP_DIR}/src/config.cpp")
    else()
        file(GLOB generated_c CONFIGURE_DEPENDS "${G_GENERATED}/funcs_*.c")
        set(game_sources ${generated_c} "${RECOMP_DIR}/ps1_sections.cpp" "${G_SECTION_FILES}")
    endif()
    file(GLOB host_sources CONFIGURE_DEPENDS "${PORT_DIR}/host/win32/*.c")
    set(module ps1w_module_${G_NAME}_recomp)
    file(WRITE "${GEN_DIR}/ps1w_default_module.c.new"
        "/* Generated by Ps1Recomp.cmake - the game the standalone program runs. */\n#include \"ps1w_module.h\"\nextern const Ps1wModule ${module};\nconst Ps1wModule *const ps1w_default_module = &${module};\n")
    file(COPY_FILE "${GEN_DIR}/ps1w_default_module.c.new" "${GEN_DIR}/ps1w_default_module.c" ONLY_IF_DIFFERENT)
    # the game: everything but the host (the addon has its own: Source/Wasm, Ps1GuestHost)
    set(target ${G_NAME}_recomp_game)
    add_library(${target} STATIC ${w2c_c} "${HLE_DIR}/ps1_hle_wrappers.c"
        "${RECOMP_DIR}/recomp_ps1.c" "${RECOMP_DIR}/recomp_libc.c" ${game_sources})
    target_include_directories(${target} PRIVATE "${G_GENERATED}" "${RECOMP_DIR}/include" "${HLE_DIR}"
        "${PORT_DIR}/include" "${GEN_DIR}" "${SOURCE_WASM_DIR}")
    target_compile_definitions(${target} PRIVATE
        "PS1R_NAME=\"${G_NAME}\"" "PS1R_PACKAGE=\"${G_PACKAGE}\"" "PS1R_TITLE=\"${G_TITLE}\""
        "PS1R_DISC_NAME=\"${disc_name}\"" "PS1R_MODULE=${module}")
    target_compile_options(${target} PRIVATE -O2 -g -w)
    set_target_properties(${target} PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED ON)
    # the standalone program
    add_executable(${G_NAME}_recomp ${host_sources} "${PORT_DIR}/host/wasm_standalone/ps1w_standalone.c"
        "${SOURCE_WASM_DIR}/ps1w_rt.c" "${SOURCE_WASM_DIR}/ps1w_backend.c" "${SOURCE_WASM_DIR}/ps1w_gpu.c"
        "${SOURCE_WASM_DIR}/ps1w_disc.c" "${GEN_DIR}/ps1w_default_module.c")
    target_include_directories(${G_NAME}_recomp PRIVATE "${PORT_DIR}/include" "${GEN_DIR}" "${SOURCE_WASM_DIR}")
    target_compile_options(${G_NAME}_recomp PRIVATE -O2 -g -w)
    target_link_libraries(${G_NAME}_recomp PRIVATE ${target})
    # the libraries call function pointers the game gave them through ps1w_guest_callback
    set_source_files_properties(${w2c_c} PROPERTIES COMPILE_DEFINITIONS "PS1W_RECOMP=1")
    # the game's calls to PsyQ functions (by name) need their declarations
    if(generated_c)
        set_source_files_properties(${generated_c} PROPERTIES
            COMPILE_OPTIONS "-fno-strict-aliasing;-include;${HLE_DIR}/ps1_hle_decls.h"
            OBJECT_DEPENDS "${HLE_DIR}/ps1_hle_decls.h")
    endif()
    if(PS1_RECOMP_LIVE)
        target_compile_definitions(${target} PRIVATE PS1R_LIVE=1 "PS1R_DATA_DIR=\"${G_SYMS}\"")
        target_include_directories(${target} PRIVATE "${PS1_N64RECOMP_DIR}/src")
        target_link_libraries(${target} PUBLIC LiveRecomp N64Recomp SymbolLists tomlplusplus::tomlplusplus)
        # one library for the addon: the game library and the recompiler's merged
        set(merged "${CMAKE_CURRENT_BINARY_DIR}/${G_NAME}_recomp_all${CMAKE_STATIC_LIBRARY_SUFFIX}")
        set(parts $<TARGET_FILE:${target}> $<TARGET_FILE:LiveRecomp> $<TARGET_FILE:N64Recomp>
            $<TARGET_FILE:SymbolLists> $<TARGET_FILE:rabbitizer> $<TARGET_FILE:fmt>)
        get_filename_component(tool_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
        find_program(PS1_RECOMP_LIB_TOOL NAMES llvm-lib lib HINTS "${tool_dir}" REQUIRED)
        add_custom_command(OUTPUT "${merged}" COMMAND "${PS1_RECOMP_LIB_TOOL}" /nologo "/out:${merged}" ${parts}
            DEPENDS ${target} LiveRecomp N64Recomp SymbolLists rabbitizer fmt
            COMMENT "merging ${G_NAME}_recomp_all" VERBATIM)
        add_custom_target(${G_NAME}_recomp_all ALL DEPENDS "${merged}")
    endif()
    target_link_libraries(${G_NAME}_recomp PRIVATE kernel32 user32 gdi32 winmm xinput)
    target_link_options(${G_NAME}_recomp PRIVATE -fuse-ld=lld -Wl,/debug)
endfunction()
