#!/usr/bin/env python3
"""Generate ps1_symbols.c: fallbacks for symbols the PS1 link resolved by address.

The decomp's symbol files map names to PS1 addresses. In the native build PS1
RAM is mapped at its real address and the original executable and overlay
files are loaded into it, so a *data* symbol that no C file defines can simply
resolve to its original address. Each one becomes an absolute symbol bound with
/ALTERNATENAME, which only takes effect when nothing else defines the name.

Function symbols are left out on purpose: those must be implemented natively,
and the link error says which ones are missing (also written to
missing_functions.txt for reference).

Usage: gen_symbols.py <decomp_dir> <version> <out_dir> [--ram-size=N]
"""
import os
import re
import sys

import yaml


def code_ranges(config_dir):
    """VRAM ranges holding code, per segment config."""
    ranges = []
    for name in sorted(os.listdir(config_dir)):
        if not name.endswith(".yaml") or name in ("bss.yaml", "sbss.yaml"):
            continue
        with open(os.path.join(config_dir, name)) as f:
            cfg = yaml.safe_load(f)
        for seg in cfg.get("segments", []):
            if not isinstance(seg, dict) or seg.get("type") != "code":
                continue
            delta = seg["vram"] - seg["start"]
            subs = [s for s in seg.get("subsegments", []) if isinstance(s, list) and len(s) >= 2]
            # code: c/asm and library objects' text ([start, o, name] or [start, o, name, .text])
            def is_code(s):
                return s[1] in ("c", "asm", "hasm") or (s[1] == "o" and (len(s) < 4 or s[3] == ".text"))
            starts = [s[0] for s in subs if is_code(s)]
            ends = [s[0] for s in subs if not is_code(s) and s[1] != "pad"]
            if starts:
                end = min([e for e in ends if e > min(starts)] or [max(starts) + 0x100000])
                ranges.append((min(starts) + delta, end + delta))
    return ranges


def overlay_starts(config_dir):
    """<overlay>_START: VRAM of the first segment of each overlay config."""
    starts = {}
    for name in sorted(os.listdir(config_dir)):
        if not name.endswith(".yaml") or name in ("main.yaml", "bss.yaml", "sbss.yaml"):
            continue
        if not re.match(r"^\w+\.yaml$", name):
            continue  # not an overlay (e.g. a single-executable game's splat.<exe>.yaml)
        with open(os.path.join(config_dir, name)) as f:
            cfg = yaml.safe_load(f)
        segs = [s for s in cfg.get("segments", []) if isinstance(s, dict)]
        if segs:
            ovl = name[:-5]
            starts[f"{ovl}_START"] = segs[0]["vram"]
            for seg in segs:
                if seg.get("name") == "header":
                    starts[f"{ovl}_HEADER"] = seg["vram"]
    return starts


RAM_BASE, RAM_SIZE = 0x80000000, 0x200000  # RAM_SIZE: --ram-size (ps1_add_game RAM_SIZE)


def write_wasm_symbols(data, path):
    """wasm build: wasm-ld has no absolute symbols, so PS1 RAM is a 2 MB placeholder
    at the very start of .rodata (this object is linked first, --global-base is
    0x80000000) and every data symbol is a weak label at its offset in it. A C
    definition of the same name wins, like /ALTERNATENAME in the native build."""
    syms = sorted((addr - RAM_BASE, sym) for sym, addr in data.items())
    outside = [f"{s}=0x{o + RAM_BASE:08X}" for o, s in syms if not 0 <= o < RAM_SIZE]
    if outside:
        sys.exit("gen_symbols.py: data symbols outside PS1 RAM are not supported in the wasm build: "
                 + " ".join(outside[:10]))
    lines = ["# Generated by gen_symbols.py - do not edit.",
             '\t.section .rodata.0ps1_ram,"",@', "\t.globl ps1_ram", "\t.p2align 4", "ps1_ram:"]
    pos = 0
    for offset, sym in syms:
        if offset > pos:
            lines.append(f"\t.skip {offset - pos}")
            pos = offset
        lines += [f"\t.weak {sym}", f"{sym}:"]
    lines.append(f"\t.skip {RAM_SIZE - pos}")
    lines.append(f"\t.size ps1_ram, {RAM_SIZE}")
    for i, (offset, sym) in enumerate(syms):
        nxt = next((o for o, _ in syms[i + 1:] if o > offset), RAM_SIZE)
        lines.append(f"\t.size {sym}, {nxt - offset}")
    text = "\n".join(lines) + "\n"
    if not os.path.exists(path) or open(path).read() != text:
        with open(path, "w", newline="\n") as f:
            f.write(text)


def main():
    global RAM_SIZE
    for arg in sys.argv[4:]:
        if arg.startswith("--ram-size="):
            RAM_SIZE = int(arg.split("=", 1)[1], 0)
    decomp, version, out_dir = os.path.abspath(sys.argv[1]), sys.argv[2], sys.argv[3]
    config_dir = os.path.join(decomp, "config", version)
    ranges = code_ranges(config_dir)
    syms = {}
    for name in sorted(os.listdir(config_dir)):
        if name.startswith("symbols") and name.endswith(".txt"):
            with open(os.path.join(config_dir, name)) as f:
                for line in f:
                    m = re.match(r"\s*(\w+)\s*=\s*(0x[0-9A-Fa-f]+)\s*;(.*)", line)
                    if m and "ignore:true" not in m.group(3):
                        syms[m.group(1)] = (int(m.group(2), 16), "type:func" in m.group(3))
    data, funcs = {}, {}
    for sym, (addr, is_func) in syms.items():
        if is_func or any(lo <= addr < hi for lo, hi in ranges):
            funcs[sym] = addr
        else:
            data[sym] = addr
    for sym, addr in overlay_starts(config_dir).items():
        data.setdefault(sym, addr)

    os.makedirs(out_dir, exist_ok=True)
    write_wasm_symbols(data, os.path.join(out_dir, "ps1_symbols.s"))
    lines = ["/* Generated by gen_symbols.py - do not edit. */", "__asm__("]
    for sym in sorted(data):
        lines.append(f'    ".globl ___dwabs_{sym}\\n.set ___dwabs_{sym}, 0x{data[sym]:08X}\\n"')
    lines.append(");")
    # Linker directives written straight into .drectve: the game is compiled for the
    # GNU target (GCC struct layout), where #pragma comment(linker) is ignored.
    lines.append('__asm__(".section .drectve,\\"yn\\"\\n"')
    for sym in sorted(data):
        lines.append(f'    ".ascii \\" /alternatename:_{sym}=___dwabs_{sym}\\"\\n"')
    lines.append('    ".text\\n");')
    text = "\n".join(lines) + "\n"
    path = os.path.join(out_dir, "ps1_symbols.c")
    if not os.path.exists(path) or open(path).read() != text:
        with open(path, "w", newline="\n") as f:
            f.write(text)
    with open(os.path.join(out_dir, "function_symbols.txt"), "w", newline="\n") as f:
        for sym in sorted(funcs, key=lambda s: funcs[s]):
            f.write(f"{sym} 0x{funcs[sym]:08X}\n")
    print(f"{len(data)} data fallbacks, {len(funcs)} function symbols -> {out_dir}")


if __name__ == "__main__":
    main()
